#!/bin/sh
#
#   Copyright 2012 Jonathan M. Reid. See LICENSE.txt
#   Created by: Jon Reid, http://qualitycoding.org/
#   Source: https://github.com/jonreid/XcodeCoverage
#

source envcov.sh


generate_report()
{
	cd "${OBJ_DIR}"
 	gcovr . -x > "${SRCROOT}"/coverage.xml    
}

generate_report
